# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

target 'SimpleFirebase' do
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
